# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Artsy Engineering
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "/blog/:num/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

authors:
  orta:
    name: Orta Therox
    site: http://orta.io
    twitter: orta
    github: orta
    byline: Code Janitor at Artsy, thinking about JS tooling.

  db:
    name: Daniel Doubrovkine
    site: http://code.dblock.org
    twitter: dblockdotorg
    github: dblock

  ash:
    name: Ash Furrow
    github: ashfurrow
    twitter: ashfurrow
    site: http://ashfurrow.com

  lily:
    name: Lily Pace
    github: lilyfromseattle
    twitter: lilyfromseattle
    site: http://lilyfromseattle.com

  joey:
    name: Joey Aghion
    github: joeyAghion
    twitter: joeyAghion
    site: http://joey.aghion.com

  eloy:
    name: Eloy Durán
    github: alloy
    twitter: alloy

  sarahscott:
    name: Sarah Scott
    github: sarahscott

  sarahweir:
    name: Sarah Weir
    github: sweir27
    twitter: sweir27

  laura:
    name: Laura Brown
    github: laurabrown

  brennan:
    name: Brennan Moore
    github: zamiang
    twitter: zamiang

  ilya:
    name: Ilya Kavalerov
    github: ilyakava
    twitter: ilyakava
    site: http://ilyakavalerov.com

  craig:
    name: Craig Spaeth
    github: craigspaeth
    twitter: craigspaeth

  matt:
    name: Matt Zikherman
    github: mzikherman
    twitter: mzikherman

  anil:
    name: Anil Bawa-Cavia
    github: cavvia
    twitter: cavvia
    site: http://cavvia.net

  frank:
    name: Frank MacReery

  gib:
    name: Gilbert Reimschüssel (gib)
    github: gib
    twitter: greims
    site: http://shortforgilbert.com

  mattm:
    name: Matt McNierney
    github: mmcnierney14
    twitter: mmcnierney
    site: http://mattmcnierney.wordpress.com

  barry:
    name: Barry Hoggard
    github: bhoggard
    twitter: bhoggard
    site: http://tristanmedia.com/

  maxim:
    name: Maxim Cramer
    github: mennenia
    twitter: mennenia
    site: http://www.mennenia.com

  alan:
    name: Alan Johnson
    github: acjay
    twitter: AlanJay1

  ashkan:
    name: Ashkan Nasseri
    github: ashkan18
    twitter: ashkinas

  kana:
    name: Kana Abe
    github: kanaabe
    twitter: kana_abe

  eve:
    name: Eve Essex
    github: eessex
    twitter: seevexes

  chris:
    name: Christopher Pappas
    github: damassi
    # twitter: damassi

  yayoi:
    name: Yayoi Shionoiri
    twitter: yayoi_shionoiri

  erik:
    name: Erik Stockmeier
    github: erikdstock
    twitter: erikdstock

  artsy:
    name: Artsy

  artsy_engineering:
    name: The Artsy Engineering Team
    site: http://artsy.github.io
    twitter: ArtsyOpenSource

  nik:
    name: Nik from Graphcool
    site: http://graph.cool
    twitter: graphcool

  roop:
    name: Roop
    site: http://anandarooproy.com

  xtina:
    name: Chrinstina Thompson
    site: http://christinasthompson.com/
    twitter: Xtina_Starr
    github: xtina-starr

  chungyi:
    name: Chung-Yi Chi
    github: starsirius

  yuki:
    name: Yuki Nishijima
    github: yuki24
    twitter: yuki24

  jonallured:
    name: Jon Allured
    site: http://jonallured.com
    twitter: jonallured
    github: jonallured

  luc:
    name: Luc Succes
    github: l2succes
    twitter: lucsucces

  sibelius:
    name: Sibelius Seraphini
    github: sibelius
    twitter: sseraphini
    byline: Full Stack Developer from São Paulo.

  anson:
    name: Anson Wang
    github: ansor4

  myk:
    name: Mykola Bilokonsky
    github: mbilokonsky
    twitter: mykola
    site: https://myk.af

  justin:
    name: Justin Bennett
    github: zephraph
    twitter: zephraph

  david:
    name: David Sheldrick
    github: ds300
    twitter: djsheldrick

  matt-dole:
    name: Matt Dole
    github: mdole

  steve-hicks:
    name: Steve Hicks
    github: pepopowitz
    twitter: pepopowitz
    site: https://stevenhicks.me

  ashley:
    name: Ashley Jelks
    github: ashleyjelks
    twitter: AshTheYogiDev

  adam:
    name: Adam Iskounen
    github: iskounen

  will:
    name: Will Doenlen
    github: williardx
    twitter: willdoenlen
    site: https://willdoenlen.com

  daniel:
    name: Daniel Levenson
    github: dleve123

  anna:
    name: Anna Carey
    github: annacarey
    twitter: anna_carey
    site: https://www.annajcarey.com
